# Generated by Django 5.0.6 on 2024-05-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Email',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
