# Generated by Django 5.0.6 on 2024-05-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_notes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
